apiVersion: dns.gcp.crossplane.io/v1alpha1
kind: Policy
metadata:
  name: ruhika-policy
spec:
  forProvider:
    name: ruhika111-policy
    description: my policy
    enableInboundForwarding: true
  providerConfigRef:
    name: default
